### ISSUE TITLE
Choose a template for website to start

### ISSUE THREAD

**Issue by yancyn** [xponenthub/xponenthub.github.io#1]
Determine a good website template as our building block to start is faster then build up from zero. You can provide any html good sample, responsive with bootstrap supported or jekyll template https://github.com/jekyll/jekyll/wiki/sites.

**Comment by yancyn** [comment]
Found more list at:
- http://jekyllthemes.org/
- http://startbootstrap.com/template-categories/all/

I've shortlisted as below:
1. Creative Theme
2. [Skinny Bones](http://mmistakes.github.io/skinny-bones-jekyll/)
3. [Landing Page](http://shaneweng.com/landing-page-theme/)
4. [Freelancer](http://jekyllthemes.org/themes/freelancer/)
5. [Agency](http://startbootstrap.com/template-overviews/agency/)
6. [Architect](https://github.com/pietromenna/jekyll-architect-theme)
7. [Clean](http://jekyllthemes.org/themes/clean/)
8. [UX Academy](https://github.com/uxacademy/uxacademy.github.io)

**Comment by thryvos** [comment]
From this link https://github.com/jekyll/jekyll/wiki/sites, i have shortlisted 2:
1. http://apptamers.com/
2. http://phlow.github.io/feeling-responsive/

Jawbone website also not bad, it list all the product at 1st page, after you clicked the product will link to new page.
https://jawbone.com/

From your shortlisted list, i prefer:
3. Landing Page

**Comment by yancyn** [comment]
Confirm to use Jawbone template contains:
- Menu: Home | About Us | Prodcuts | Contact Us
- Footer - Social account: Facebook, Gmail, Github.
  - NO twitter at this moment.
- Disclaimer put together during deliver product but not in website.

**Comment by yancyn** [comment]
Pick a [landing page](http://startbootstrap.com/template-overviews/landing-page/) as a startup then modify to like [Jawbone theme](https://jawbone.com).
