### ISSUE TITLE
Webpage Display Arrangment

### ISSUE THREAD

**Issue by thryvos** [xponenthub/xponenthub.github.io#6]
- Need to correct the Facebook link for xponenethub (https://www.facebook.com/XponentHub-1028786677177888/?fref=ts), currently shown error link
- Suggestion: The XponentHub's logo, "About, Product and Contact" word should be at vertical center.
- Suggestion: Update the font style for "XponentHub" which in the photo. May be same as the logo font style. Not sure suitable, since cannot imagine now.
- At the footer, the words should have space between Company and About Us, Products and Yuan, Support and Support. May refer to Jawbone website.

**Comment by yancyn** [comment]
All completed except issue #7 has been created.
